# Numpy and Pandas

In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(5,30,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [7]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [10]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(2,4)

array([[0.5265547 , 0.39380343, 0.33401199, 0.13416977],
       [0.60052274, 0.24148882, 0.20126026, 0.03715337]])

In [13]:
np.random.rand(2,7)

array([[0.30824818, 0.45672743, 0.99032952, 0.33339352, 0.12407841,
        0.19137463, 0.45903478],
       [0.82369864, 0.59292859, 0.21672025, 0.61443129, 0.26913908,
        0.08837663, 0.5279531 ]])

In [14]:
np.random.randint(2,10)

9

In [15]:
np.random.randint(20,56,100)

array([36, 41, 52, 25, 28, 34, 31, 39, 42, 40, 45, 50, 45, 28, 20, 44, 38,
       40, 53, 39, 48, 33, 21, 51, 55, 34, 50, 25, 38, 20, 48, 53, 31, 27,
       28, 38, 50, 38, 25, 35, 42, 27, 40, 42, 43, 52, 38, 44, 39, 54, 33,
       39, 26, 36, 40, 50, 26, 21, 37, 24, 41, 34, 38, 28, 26, 48, 55, 31,
       38, 32, 52, 37, 35, 42, 26, 42, 29, 29, 41, 21, 28, 37, 30, 28, 50,
       55, 45, 53, 29, 42, 55, 54, 22, 48, 34, 34, 40, 38, 37, 29])

In [16]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
rand_array=np.random.randint(0,100,20)
rand_array

array([12, 39, 45, 75, 44,  7, 28, 46, 45, 91, 59, 50, 20,  9,  7, 97, 53,
       51, 32, 50])

In [18]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [19]:
rand_array.max()

97

In [20]:
rand_array.argmax()

15

In [21]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sample_array.shape

(30,)

In [23]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
sample_array.dtype

dtype('int32')

In [25]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.random.rand(2,3)
a

array([[0.98027692, 0.32324206, 0.11789996],
       [0.0798759 , 0.98603683, 0.4829914 ]])

In [28]:
a.T

array([[0.98027692, 0.0798759 ],
       [0.32324206, 0.98603683],
       [0.11789996, 0.4829914 ]])

In [29]:
import numpy as np

In [30]:
sample_array=np.arange(10,21)


In [31]:
sample_array[8]

18

In [32]:
sample_array[2:5]

array([12, 13, 14])

In [33]:
sample_array[[2,5]]

array([12, 15])

In [34]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [35]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [36]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [38]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [39]:
sample_matrix[0][2]

1

In [40]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [41]:
sample_matrix[2]

array([56, 76, 24,  7])

### Custom indexing

In [42]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [43]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

###  Selection techniques

In [44]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [46]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [48]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [49]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [50]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [51]:
np.max(sample_array)

30

In [52]:
np.min(sample_array)

1

In [53]:
np.argmax(sample_array)

29

In [54]:
np.argmin(sample_array)

0

In [55]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [56]:
np.std(sample_array)

8.65544144839919

In [57]:
np.var(sample_array)


74.91666666666667

In [58]:
np.mean(sample_array)

15.5

In [59]:
array=np.random.randn(3,6)
array

array([[-0.97538837, -1.16456501,  0.39522523, -1.95698668,  0.2636262 ,
        -0.60974101],
       [-0.42788778, -0.39638794, -0.17750256,  0.1942698 ,  0.8138368 ,
         0.53596128],
       [ 0.28834397,  0.16375936,  0.4876393 , -0.69906782, -0.68840645,
         1.69237308]])

In [60]:
np.round(array,decimals=2)

array([[-0.98, -1.16,  0.4 , -1.96,  0.26, -0.61],
       [-0.43, -0.4 , -0.18,  0.19,  0.81,  0.54],
       [ 0.29,  0.16,  0.49, -0.7 , -0.69,  1.69]])

In [61]:
sports=np.array(['golf','cricket','fball','cricket'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [62]:
import pandas as pd

In [63]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [64]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [65]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [66]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [67]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [68]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [69]:
sports1['cricket']

1

In [70]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [71]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [72]:
df1=pd.DataFrame(randn(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

df1['Score3']



NameError: name 'randn' is not defined

In [ ]:
df1[['Score2','Score1']]

df1['Score6']=df1['Score1']+df1['Score2']
df1



In [ ]:
df1.drop('Score5',axis=1)



In [ ]:
df1.reset_index()



In [ ]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df