In [12]:
import numpy as np

In [13]:
#create an array

In [14]:
list=[1,2,3,40]
np.array(list)

array([ 1,  2,  3, 40])

In [15]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [16]:
lists=([1,2,3],[4,5,6],[7,8,9])
np.array(lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#arange function

In [18]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(5,20,6)

array([ 5, 11, 17])

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
#linspace function

In [23]:
np.linspace(0,20)

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [25]:
np.linspace(0,20,5,dtype=int)

array([ 0,  5, 10, 15, 20])

In [26]:
#eye function

In [27]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5,dtype=str)

array([['1', '', '', '', ''],
       ['', '1', '', '', ''],
       ['', '', '1', '', ''],
       ['', '', '', '1', ''],
       ['', '', '', '', '1']], dtype='<U1')

In [29]:
np.eye(1,5)

array([[1., 0., 0., 0., 0.]])

In [30]:
np.eye(1:2,2:3)

SyntaxError: invalid syntax (<ipython-input-30-763a7b71a016>, line 1)

In [ ]:
#random function

In [ ]:
np.random.rand(2,4)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randn(2,4)

In [ ]:
#(0-10,15values)

In [ ]:
np.random.randint(0,10,15)

In [ ]:
np.random.randint(20,25,100)

In [ ]:
rand_array=np.random.randint(1,15,10)

In [31]:
sample_array=np.arange(0,20)

In [32]:
#min

In [33]:
sample_array.min()

0

In [34]:
#max

In [35]:
rand_array.max()

NameError: name 'rand_array' is not defined

In [36]:
#position of min and max

In [37]:
sample_array.argmin()

0

In [38]:
rand_array.argmax()

NameError: name 'rand_array' is not defined

In [39]:
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [40]:
print(random_array)

NameError: name 'random_array' is not defined

In [41]:
print(rand_array)

NameError: name 'rand_array' is not defined

In [42]:
rand_array=np.random.rand(1,15,10)

In [43]:
print(rand_array)

[[[0.18820703 0.34951342 0.56744917 0.41816143 0.65036552 0.86258862
   0.55057465 0.61304781 0.26466014 0.22465431]
  [0.40217157 0.81142665 0.90746457 0.18975105 0.64394401 0.78027616
   0.38921634 0.84124545 0.60105637 0.11281618]
  [0.89798855 0.18045088 0.81105049 0.29132488 0.70172535 0.50568622
   0.80061541 0.3397351  0.93789017 0.3895793 ]
  [0.94500706 0.99871952 0.40196031 0.52971914 0.05807175 0.12763809
   0.68728546 0.64573744 0.91531499 0.3830548 ]
  [0.49739093 0.27467891 0.45802067 0.93687094 0.86387441 0.96096629
   0.74107649 0.3166935  0.92540519 0.8761586 ]
  [0.74851179 0.85114238 0.86390262 0.51743626 0.02516663 0.18266629
   0.93694675 0.00463821 0.57404544 0.43678146]
  [0.63852425 0.38957047 0.3954058  0.20440787 0.61731459 0.47073739
   0.83501967 0.53553731 0.51780431 0.50581368]
  [0.01587959 0.36370768 0.81969716 0.3123483  0.68945446 0.53887629
   0.12046094 0.53592215 0.15200262 0.14751071]
  [0.06819468 0.42865987 0.28368644 0.44411536 0.13988381 0.3596

In [83]:
a=np.eye(5)

In [84]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
a.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [46]:
#transpose

In [47]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
sample_array=sample_array.reshape(2,7)

ValueError: cannot reshape array of size 20 into shape (2,7)

In [49]:
sample_array=sample_array.reshape(2,10)

In [50]:
sample_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [51]:
sample_array[3]=50

IndexError: index 3 is out of bounds for axis 0 with size 2

In [52]:
sample_array[2]=50

IndexError: index 2 is out of bounds for axis 0 with size 2

In [53]:
sample_array[1]=50

In [54]:
sample_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [56]:
sample_array[1:12]

array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [57]:
subset_sample_array=sample_array[0:7]

In [58]:
subset_sample_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

# Two dimensional array

In [61]:
matrix=np.array(([10,20,30],[40,50,60],[70,80,90]))

In [62]:
matrix

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
# matrix(row,column)

In [63]:
matrix[2][2]

90

In [64]:
matrix[1][2]

60

In [65]:
matrix[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [66]:
matrix[:3]

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [75]:
matrix[1:2][1:]

array([], shape=(0, 3), dtype=int32)

In [76]:
#

In [77]:
np.std(sample_array)

22.84047941703501

In [78]:
np.mean(sample_array)

27.25

In [79]:
np.round(sample_array)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])

In [80]:
np.round(sample_array,decimal 3)

SyntaxError: invalid syntax (<ipython-input-80-3b6dc7771fae>, line 1)

In [91]:
c=np.linspace(0,0,10,dtype=int)

In [87]:
c

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [92]:
np.arange(0,0,6)

array([], dtype=int32)